wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717336974
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      - 105
      3:
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
